services:
  # Socket Server (Node.js)
  - type: web
    name: muse-server
    env: docker
    dockerfilePath: apps/server/Dockerfile
    dockerContext: .
    plan: free
    numInstances: 1
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CLIENT_URL
        value: https://web-aryan717317s-projects.vercel.app
      - key: REDIS_URL
        sync: false
      - key: REDIS_TOKEN
        sync: false
